from pathlib import Path
import json
root = Path(__file__).resolve().parent.parent
rows = [line.split('|') for line in (root/'Localization/translations.tsv').read_text().splitlines() if line]
assert all(len(row)==4 for row in rows)
keys = [row[0] for row in rows]
assert len(keys)==len(set(keys)), 'Duplicate translation key'
tables = {'chinese':json.loads((root/'Localization/zh-Hans.json').read_text()), 'traditionalChinese':json.loads((root/'Localization/zh-Hant.json').read_text())}
for index, name in enumerate(['japanese','korean','french'],1): tables[name] = {row[0]:row[index] for row in rows}
for name, table in tables.items():
    assert set(table)==set(keys), (name, set(keys)-set(table))
    assert all(table.values())
quote=lambda s:json.dumps(s,ensure_ascii=False)
source='''// Generated by Scripts/generate-localizations.py from Localization/. Do not hand-edit tables.
import Foundation
import QuotaCore

enum AppText {
    static var allKeys: Set<String> { Set(chinese.keys) }
    static func table(_ language: AppLanguage) -> [String: String] {
        switch language {
        case .english: return [:]
        case .chinese: return chinese
        case .traditionalChinese: return traditionalChinese
        case .japanese: return japanese
        case .korean: return korean
        case .french: return french
        }
    }
    static func value(_ key: String, _ language: AppLanguage) -> String {
        guard language != .english else { return key }
        let prefix = "Configured QuotaClock widgets: "
        if key.hasPrefix(prefix) {
            let labels: [AppLanguage:String] = [.chinese:"已添加的 QuotaClock 小组件：", .traditionalChinese:"已加入的 QuotaClock 小工具：", .japanese:"設定済みの QuotaClock ウィジェット：", .korean:"설정된 QuotaClock 위젯: ", .french:"Widgets QuotaClock configurés : "]
            return (labels[language] ?? prefix) + key.dropFirst(prefix.count)
        }
        return table(language)[key] ?? key
    }
'''
for name,table in tables.items():
    source+='    private static let '+name+': [String:String] = [\n'+',\n'.join('        '+quote(k)+': '+quote(v) for k,v in table.items())+'\n    ]\n'
source+='}\n'
(root/'Sources/Shared/AppText.swift').write_text(source)
print('Generated',len(tables),'complete translation tables;',len(keys),'keys each')
